# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-raVYRnZXEutn7q2sAhstF6XYhwrh_B
"""

import numpy as np
import pandas as pd

data = pd.read_csv('/content/Iris.csv')

data.head()

X = data[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
Y = data['Species']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, train_size = 0.8, random_state = 42)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train, y_train)

model.predict([[4.9,3.0,1.4,0.2]])